# Generated by Django 4.2.27 on 2026-02-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omlights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_priority",
            field=models.BooleanField(default=False),
        ),
    ]
