# Generated by Django 4.2.27 on 2026-02-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omlights", "0002_product_is_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
