# Generated by Django 4.2.27 on 2026-02-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omlights", "0004_customer_order_alter_product_category_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
