# Generated by Django 4.2.27 on 2026-02-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omlights", "0005_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="razorpay_signature",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
