# Generated by Django 4.2.27 on 2026-02-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omlights", "0006_order_razorpay_order_id_order_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True),
        ),
    ]
