# Generated by Django 4.2.27 on 2026-03-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("omlights", "0007_product_in_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_to", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "applicable_products",
                    models.ManyToManyField(
                        blank=True, related_name="promo_codes", to="omlights.product"
                    ),
                ),
            ],
        ),
    ]
